### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/robot/catkin_ws/src/point_cloud_segmentation-master/pcs_detection/scripts/example_data/trained_hist.npy'

### ISSUE THREAD

**Issue by dbdxnuliba** [swri-robotics/point_cloud_segmentation#25]
after catkin build sucess ,
I roslaunch pcs_ros demo.launch 
`
<?xml version="1.0" ?>
<launch>
  <arg name="cloud_path" default="$(find pcs_ros)/test/data/colorized_cloud1.bag"/>
  <arg name="use_pcd" default="false" />
  <arg name="viz" default="true" />
  <arg name="hist_backproject" default="true" />

  
  <group if="$(arg use_pcd)">
    <remap from="cloud_pcd" to="unmasked_cloud" />
    <node pkg="pcl_ros" type="pcd_to_pointcloud" name="simulated_scanner" output="screen" args="$(arg cloud_path) 1">
      <param name="frame_id" value="base_link"/>
    </node>
  </group>
  
  <group unless="$(arg use_pcd)">
    <remap from="/camera/depth_registered/points" to="pc_masker_node/unmasked_cloud" />
    <node pkg="rosbag" type="play" name="rosbag_player" args="--clock --loop $(arg cloud_path)"/>
  </group>

  
  <node unless="$(arg hist_backproject)" pkg="pcs_ros" type="pcs_ros_hsv_thresholding_node" name="hsv_threshold_node" output="screen" />
  <node if="$(arg hist_backproject)" pkg="pcs_ros" type="histogram_backprojection_node" name="histogram_backprojection_node" output="screen" >
      <param name="filepath" value="$(find pcs_detection)/scripts/example_data/trained_hist.npy"/>
  </node>

  
  <node if="$(arg viz)" name="rviz" type="rviz" pkg="rviz" args="-d $(find pcs_ros)/config/demo.rviz" output="screen"/>

  
  <node pkg="image_view" type="image_saver" name="image_saver" output="screen" >
    <param name="filename" value="$(find pcs_detection)/data/%04i.png" />
    <param name="encoding" value="bgr8" />
    <param name="save_all_image" value="false" />
  </node>

</launch>`

the teriminal shows 
Traceback (most recent call last):
  File "/home/robot/catkin_ws/src/point_cloud_segmentation-master/pcs_ros/src/histogram_backprojection_node", line 53, in <module>
    server = HistogramBackprojectionServer(filepath)
  File "/home/robot/catkin_ws/src/point_cloud_segmentation-master/pcs_ros/src/histogram_backprojection_node", line 23, in __init__
    self.histogram_backprojection = HistogramBackprojection(filepath)
  File "/home/robot/catkin_ws/devel/lib/python3/dist-packages/pcs_detection/models/histogram_backprojection.py", line 19, in __init__
    self.histogram = np.load(hist_filepath)
  File "/home/robot/.local/lib/python3.8/site-packages/numpy/lib/npyio.py", line 417, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: '/home/robot/catkin_ws/src/point_cloud_segmentation-master/pcs_detection/scripts/example_data/trained_hist.npy'
[histogram_backprojection_node-2] process has died [pid 275489, exit code 1, cmd /home/robot/catkin_ws/src/point_cloud_segmentation-master/pcs_ros/src/histogram_backprojection_node __name:=histogram_backprojection_node __log:=/home/robot/.ros/log/1a756414-37fe-11ed-b265-b1452c6111fe/histogram_backprojection_node-2.log].
log file: /home/robot/.ros/log/1a756414-37fe-11ed-b265-b1452c6111fe/histogram_backprojection_node-2*.log

**Comment by mpowelson** [comment]
The python modules are supposed to be getting installed when you catkin build. Did you source your setup.bash after you built?

**Comment by dbdxnuliba** [comment]
yes , i did , and it shows  FileNotFoundError: [Errno 2] No such file or directory: '/home/robot/catkin_ws/src/point_cloud_segmentation-master/pcs_detection/scripts/example_data/trained_hist.npy'

but i can't find the  file in the pcs_detection package :
![image](https://user-images.githubusercontent.com/13350158/191144734-4c3200e8-7146-4b90-a623-a3300970ac7f.png)

I download the  pkg in the master branch 

> The python modules are supposed to be getting installed when you catkin build. Did you source your setup.bash after you built?

**Comment by dbdxnuliba** [comment]
more details, after I catkin build the workspace , pcs_detection install into /home/robot/ws_tesseract_new/devel/lib/python3/dist-packages
![image](https://user-images.githubusercontent.com/13350158/191145555-541a8026-a492-495c-a784-ed0a32aaad4f.png)

it there has also not trained_hist.npy

**Comment by mpowelson** [comment]
Oh I see. It looks like that is the histogram that is "trained" from the dataset and used for histogram backprojection. This repo was set up to either use that or fcn8. It looks like I didn't include any of the trained models here. I'm not immediately seeing the code to generate the histogram, but you can see [this](https://docs.opencv.org/4.x/dc/df6/tutorial_py_histogram_backprojection.html) example. Basically I think you want the output of `roihist = cv.calcHist([hsv],[0, 1], None, [180, 256], [0, 180, 0, 256] )` saved to a pickle.
